# Generated by Django 3.0.4 on 2020-05-13 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_auto_20200512_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='when',
            field=models.DateField(default=datetime.datetime(2020, 5, 13, 15, 51, 15, 211888, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
