# Generated by Django 3.0.4 on 2020-05-13 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_auto_20200513_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='saver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spending.Saver'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='when',
            field=models.DateField(default=datetime.datetime(2020, 5, 13, 18, 20, 35, 774503, tzinfo=utc)),
        ),
    ]
