# Generated by Django 3.0.4 on 2020-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=8)),
                ('when', models.DateTimeField(verbose_name='spense_date')),
            ],
        ),
    ]
