# Generated by Django 3.0.4 on 2020-05-12 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_auto_20200511_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='when',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 18, 58, 6, 282738, tzinfo=utc)),
        ),
    ]
